package com.example.babysdiet.ui.theme

import androidx.compose.ui.unit.dp

val DIARY_ITEM_ELEVATION = 2.dp

val EVALUATOIN_INDICATOR_SIZE = 16.dp
val BIG_EVALUATOIN_INDICATOR_SIZE = 42.dp
val DATE_PICKER_HEIGTH = 50.dp
val LAZY_GRID_HEIGHT = 100.dp
val LAZY_GRID_COLUMN_WIDTH = 100.dp
val TOP_APP_BAR_HEIGHT_LARGE = 88.dp
val TOP_APP_BAR_HEIGHT = 64.dp
val TOP_APP_BAR_HEIGHT_SMALL = 56.dp
val OUTLINEDBUTTON_HEIGHT = 28.dp
val OUTLINEDBUTTON_HEIGHT_SMALL = 20.dp
val FOOD_ACTIVITIES_HEIGHT = 150.dp

val ULTRA_LARGE_PADDING = 24.dp
val LARGE_PADDING = 12.dp
val MEDIUM_PADDING = 8.dp
val SMALL_PADDING = 6.dp
val VERY_SMALL_PADDING = 1.dp